version: '3.9'

services:
#  api-registration:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    container_name: api-registration
#    environment:
#      API_PORT: 8080
#      DATABASE_URL: postgres:5432
#      DATABASE_DB: "voy"
#      DATABASE_USER: postgres
#      DATABASE_PASSWORD: password
#      DATABASE_SCHEMA: registration
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres

  postgres:
    container_name: postgres_registration
    image: 'postgres:alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./src/main/resources/db/create_database_voy.sql:/docker-entrypoint-initdb.d/create_database_voy.sql
      - ./src/main/resources/db/create_schema_registration.sql:/docker-entrypoint-initdb.d/create_schema_registration.sql
