version: '3.9'
services:
  app:
    build: .
    container_name: ms_registration_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      PROFILE_ACTIVE: dev
      API_PORT: 8080
      DATABASE_DB: voy
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_SCHEMA: registration
      PLACES_API_KEY: ${PLACES_API_KEY}
      EARTH_RADIUS_KM: 6371
      INCREMENTAL_BOUNDING_BOX_RADIUS_KM: 5
      INITIAL_DEFAULT_BOUNDING_BOX_RADIUS_KM: 10
      LIMIT_MAX_BOUNDING_BOX: 100
      MAX_PLACE_SIZE_LIST: 5

  postgres:
    container_name: postgres_registration
    image: 'postgres:alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voy
    volumes:
      - ./src/main/resources/db/create_schema_registration.sql:/docker-entrypoint-initdb.d/create_schema_registration.sql
